apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-react-app-template
  title: Create React App Template
  description: Create a new CRA website project
  tags:
    - react
    - cra
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Provide some simple information
      properties:
        viaops:
          title: Squad
          type: string
          description: Selecione a sua squad
          ui:field: ViaOpsSelectSquad
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.

  steps:
    - id: debug
      if: ${{ true === true }}
      name: Debug
      action: debug:log
      input:
        message: ${{ parameters.description }}
        extra: ${{ parameters.viaops }}
